services:
  - type: web
    name: pawn-shop-app
    env: php
    buildCommand: ""
    startCommand: "docker build -t pawn-shop-image . && docker run -p 80:80 pawn-shop-image"
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: "rootpassword"
      - key: MYSQL_DATABASE
        value: "store_db"
      - key: MYSQL_USER
        value: "myuser"
      - key: MYSQL_PASSWORD
        value: "mypassword"
    autoDeploy: true
